#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..
# cp -r ./templates package/
cp -r ./jenkins package/

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-linkmode external -extldflags -static -s"
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o bin/pipeline
