#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-v3}
#${VERSION}${SUFFIX}}
REPO=${REPO:-reg.cnrancher.com/rancher}

cp ../bin/pipeline .
docker build -t ${REPO}/pipeline:${TAG} .

echo Built ${REPO}/pipeline:${TAG}

docker login -u admin -p "Rancher@123" -e "lawrence@rancher.com" ${REPO}
docker push ${REPO}/pipeline:${TAG}

