#!/bin/bash
set -e

echo Running package
source $(dirname $0)/version

mkdir -p $(dirname $0)/../dist && rm -rf $(dirname $0)/../dist/*

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package
cp ../bin/pipeline ./pipeline/

TAG=${TAG:-dev}
#${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

Folders="$(dirname $0)/../package"

for Folder_a in ${Folders}/*; do
  Folder_a_name=`echo "$Folder_a" | awk -F '\/' '{print $NF}'`
  docker build -t ${REPO}/${Folder_a_name}:${TAG} $Folder_a/.
  echo ${REPO}/${Folder_a_name}:${TAG} >> $(dirname $0)/../dist/images
done
cat $(dirname $0)/../dist/images